apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-3tier.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp-3tier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "webapp-3tier.selectorLabels" . | nindent 4 }}
